name: zerospeech2021_test
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - cudatoolkit=9.2
  - cython
  - nose
  - numpy
  - openblas-devel
  - pip
  - psutil
  - pysoundfile
  - pytorch=1.7.1
  - torchvision
  - torchaudio=0.7.2
  - tqdm
  - pip:
      - progressbar2
